---
- name: add repo for docker
  yum_repository:
    name: Docker-CE
    description: Docker-ce stable
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
- name: install docker and tools
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
- name: enable docker
  service:
    name: docker
    state: started
    enabled: yes